import React, { useState, useRef } from "react";
import { QRCodeCanvas } from "qrcode.react";
import { X, Download, Copy, Check } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useToast } from "./Toast";
import { type UrlItem } from "../hooks/useUrls";

interface QrCodeModalProps {
  urlItem: UrlItem | null;
  onClose: () => void;
}

const PRESET_COLORS = [
  { name: "Sleek Black", value: "#000000" },
  { name: "Royal Indigo", value: "#312E81" },
  { name: "Secure Violet", value: "#7C3AED" },
  { name: "Forest Emerald", value: "#065F46" },
  { name: "Crimson Red", value: "#991B1B" },
];

export const QrCodeModal: React.FC<QrCodeModalProps> = ({ urlItem, onClose }) => {
  const { showToast } = useToast();
  const [fgColor, setFgColor] = useState("#000000");
  const [copied, setCopied] = useState(false);
  const qrRef = useRef<HTMLDivElement>(null);

  if (!urlItem) return null;

  // Derive full shortened URL
  const fullShortUrl = `${window.location.origin}/${urlItem.shortCode}`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(fullShortUrl);
      setCopied(true);
      showToast("Short link copied to clipboard", "success");
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      showToast("Failed to copy link", "error");
    }
  };

  const handleDownload = () => {
    // Select the canvas generated by qrcode.react
    const canvas = qrRef.current?.querySelector("canvas");
    if (!canvas) {
      showToast("Failed to generate QR Code download payload.", "error");
      return;
    }

    try {
      const url = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = url;
      link.download = `qrcode-${urlItem.shortCode}.png`;
      link.click();
      showToast("QR Code downloaded successfully", "success");
    } catch (err) {
      showToast("Download failed.", "error");
    }
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop Backdrop Blur */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="fixed inset-0 bg-black/40 backdrop-blur-sm"
        />

        {/* Modal Container */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          transition={{ type: "spring", duration: 0.4 }}
          className="bg-white rounded-3xl shadow-xl w-full max-w-sm border border-gray-100 overflow-hidden z-10 p-6 space-y-6 text-gray-900 pointer-events-auto"
        >
          {/* Header */}
          <div className="flex items-center justify-between pb-2 border-b border-gray-100">
            <div>
              <h2 className="text-lg font-bold text-gray-900">QR Code Gate</h2>
              <p className="text-xs text-gray-500">Scan to access /{urlItem.shortCode}</p>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-gray-400 hover:text-gray-600 hover:bg-gray-50 transition-all"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* QR Canvas Container (Centering) */}
          <div className="flex justify-center py-4 bg-gray-50 rounded-2xl border border-gray-100/50" ref={qrRef}>
            <QRCodeCanvas
              value={fullShortUrl}
              size={200}
              bgColor={"#ffffff"}
              fgColor={fgColor}
              level={"H"}
              includeMargin={true}
              imageSettings={{
                src: "/favicon.png",
                x: undefined,
                y: undefined,
                height: 38,
                width: 38,
                excavate: true,
              }}
            />
          </div>

          {/* Color Presets Selector */}
          <div className="space-y-2">
            <label className="text-xs font-semibold text-gray-700 block">Foreground Custom Branding</label>
            <div className="flex gap-2">
              {PRESET_COLORS.map((color) => (
                <button
                  key={color.value}
                  onClick={() => setFgColor(color.value)}
                  className={`w-7 h-7 rounded-full border-2 transition-all scale-100 hover:scale-110 relative ${
                    fgColor === color.value ? "border-[#7C3AED]" : "border-transparent"
                  }`}
                  style={{ backgroundColor: color.value }}
                  title={color.name}
                >
                  {fgColor === color.value && (
                    <Check className="w-3.5 h-3.5 text-white absolute inset-0 m-auto" />
                  )}
                </button>
              ))}
            </div>
          </div>

          {/* Mini Link Display Panel */}
          <div className="flex items-center gap-2 p-3 bg-gray-50 border border-gray-100 rounded-xl">
            <span className="text-xs font-semibold text-gray-700 select-all truncate flex-grow">
              {fullShortUrl}
            </span>
            <button
              onClick={handleCopy}
              className="p-1.5 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 text-gray-500 hover:text-gray-700 transition-colors"
              title="Copy URL"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            </button>
          </div>

          {/* Action Row */}
          <button
            onClick={handleDownload}
            className="w-full py-3 bg-[#7C3AED] hover:bg-[#6D28D9] text-white text-sm font-bold rounded-xl transition-all shadow-md flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" />
            <span>Download PNG</span>
          </button>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
